vich_uploader:
    db_driver: orm


    mappings:
        livre_images:
           uri_prefix: '%livre_images%'
           upload_destination: '%kernel.project_dir%/public%livre_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
